### ISSUE TITLE
Inconsistent behavior of deps() function

### ISSUE THREAD

**Issue by jiujiucs17** [ipyflow/ipyflow#165] opened 2024-10-06 15:08 UTC
Hi,

I was trying to find a dynamic variable dependence recovery tool for python, so I've been testing ipyflow for this purpose.

For the most part the deps() function serves this purpose just fine. But I do encountered some inconsistency in some cases.

## Problem encountered: inconsistency behavior of deps()
While the code involves calling methods, the method variables (i.e. those variables defined inside a method and can only be accessed within that method) are returned in some cases but not in others, depending on how many of them are actually used.

take the following two scenarios as examples:
### scenario 1
    from ipyflow import deps
    x = ["x"]

    def func_1():
        input_val_1 = ["input_val_1"]
        input_val_2 = ["input_val_2"]

        return input_val_1

    x += func_1()
    deps(x)

in this case the output is "[<func_1>, <input_val_1>]", correct output which makes perfect sense to me. **The data dependencies within the method are exposed.**

### scenario 2
    from ipyflow import deps
    x = ["x"]

    def func_1():
        input_val_1 = ["input_val_1"]
        input_val_2 = ["input_val_2"]

        return input_val_1 + input_val_2

    x += func_1()
    deps(x)
in this case the output becomes "[<func_1>]", while I would expect both `input_val_1` and `input_val_2` to appear in the output. **The data dependencies within the method are hidden.**

Because this inconsistency is consist of outputting data dependency on different levels of lexical analysis for not fundamentally  different use cases, I think it's valuable to look at and fix it. the inconsistency also causes difficulty for my analyzation work so I would very happy to help with locating the problem and fixing it.

## Hypothesis
I tried to dig a bit to find the cause, one possible cause could be: both input_val_1 and input_val_2 are removed from output because their corresponding `Symbol` objects are marked as anonymous and don't have a sense-making name. So I'm blindly guessing the problem is rooted much closer to the front line of data dependency processing. I tried to find out where are the `Symbol` objects are instantiated but that's where I got lots in the codebase.

**Comment by smacke** [comment] 2024-10-06 17:58
Thanks for the report. Indeed, it seems like we're special casing return statements with just one symbol [here](https://github.com/ipyflow/ipyflow/blob/bbcde22a4a06c89dda90743259e81cf858781437/core/ipyflow/tracing/ipyflow_tracer.py#L456). For return statements involving multiple symbols, it looks like we create an anonymous symbol on which those depend. I'm not sure about the rationale for that -- off the top of my head, it seems like we could just as well elide this part and use the multiple symbols directly. I will do a bit more investigation.

**Comment by smacke** [comment] 2024-10-06 18:52
Just pushed a fix + release, this should be better now, please let me know if not. Thanks again for the report!

**Comment by jiujiucs17** [comment] 2024-10-07 12:13
it's resolved perfectly! thanks!

**Comment by jiujiucs17** [comment] 2024-10-08 15:54
Hi there, 

I noticed another strange behavior of the deps() function today. This time it's about the class method (both static method and instance method are involved). 

Specifically speaking, while the name of a regular method (defined outside a class) would be included in the output of deps(), names of static & instance method (defined inside a class) would be excluded, only the class name (for static method) or the instance's name (for instance method) would be included. 

## Reproduce the problem

take the following class as the basis to reproduce the problem: 

    class DummyClass:
        class_static_val = ["DummyClass.class_static_val"]

        @staticmethod
        def class_static_method():
            class_static_method_val_1 = ["DummyClass.class_static_method_val_1"]
            class_static_method_val_2 = ["DummyClass.class_static_method_val_2"]
            return class_static_method_val_1 + class_static_method_val_2

        def __init__(self):
            self.class_val_1 = ["class_val_1"]
            self.class_val_2 = ["class_val_2"]
            self.class_val_3 = ["class_val_3"]
        
        def class_instance_method(self):
            return self.class_val_1 + self.class_val_2 + self.class_val_3

if we run:

    x = []
    class_instance = DummyClass()
    x += class_instance.class_instance_method()
    deps(x)

we will get 
`[<class_instance>,
 <class_instance.class_val_2>,
 <class_instance.class_val_1>,
 <class_instance.class_val_3>]` as result. The name 'class_instance_method' is not included.

if we run:

    x = []
    x += DummyClass.class_static_method()
    deps(x)

we will get `[<DummyClass>, <class_static_method_val_1>, <class_static_method_val_2>]`, the name 'class_static_method' is also missing.

as deps() is able to return both class name and the static variables' name while needed, it's seems a bit odd it's not able to return the above methods' name. Also, considering that the method names are returned when calling a regular method defined outside a class, including the name of static and instance name is likely to provide better consistency to the usage of deps().

Let me know what you think about this! :)

**Comment by smacke** [comment] 2024-10-09 06:43
Not including `DummyClass.class_static_method` is definitely a bug -- thanks for the report!

For `class_instance.class_instance_method`, it's a bit trickier. That object `class_instance.class_instance_method` is a short-lived "method object" with a bound `__self__` -- since it's short-lived, it's not clear whether the right thing to do is to include `class_instance.class_instance_method` (which won't exist anymore), the class object `DummyClass.class_instance_method`, or the current behavior of nothing. I think probably the second option (`DummyClass.class_instance_method`) makes the most sense but this will require some thought. Unfortunately [this part of the code](https://github.com/ipyflow/ipyflow/blob/ad793d0f70e3f57d4de145e9c017e449caf9fb6e/core/ipyflow/tracing/ipyflow_tracer.py#L922) has accumulated a ton of cruft and has me scratching my own head wondering what I was thinking.

**Comment by smacke** [comment] 2024-10-13 21:28
Hey @jiujiucs17 I ended up implementing approach (2) from above and I think things should be more in line with expectations now. Please let me know if there's any other unexpected behavior, really appreciate these reports.

**Closed by smacke** 2024-10-13 21:28 UTC

**Comment by jiujiucs17** [comment] 2024-10-15 15:14
Hi @smacke thanks for the update! and sorry for my late reply! Yes I would agree that the second would make the most sense. 

I probably would also argue that it might be useful to combine the first two approach, to show the instance information `class_instance` along side the `DummyClass.class_instance_method` in a way that they are logically linked (e.g.`(class_instance)DummyClass.class_instance_method` ).

Currently they look like unrelated items in the output, and it could become confusing when the number of output grows, making the source of the reference to `DummyClass.class_instance_method` hard to pinpoint in source code(could be me being paranoid though!).

The downside of this approach is bringing in a bit more complexity to the output structure, but i personally believe it's worthwhile :)
